POST http://localhost:4444/api/auth/login
Content-Type: application/json

{
    "username": "thai",
    "password": "1234"
}

###
POST http://localhost:4444/api/auth/register
Content-Type: application/json

{
    "username": "thuy",
    "name": "thuy",
    "password": "1234"
}
###

GET http://localhost:4444/api/auth
Authorization: Bearer .eyJ1c2VySWQiOiI2MGQ4MjE5OTllOWE3MzJhMjAwZGZhZDciLCJpYXQiOjE2MjQ3NzczNTN9.Suimu-esLFttXUoXNP61PM9a1g4AwE_ym5aaiDsDoQ4

###
POST http://localhost:4444/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ4Mjk1ZmVjMzYxMzBhMThjNGI2MTAiLCJpYXQiOjE2MjQ3NzkxMDN9._f2Lvpme7dPM_QIPzjuRDgnpShpd6uS0jz5cP7BgwDU
Content-Type: application/json

{
    "title": "first",
    "description": "this is first post of Thuy"
}

###
GET http://localhost:4444/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ4Mjk1ZmVjMzYxMzBhMThjNGI2MTAiLCJpYXQiOjE2MjQ3NzkxMDN9._f2Lvpme7dPM_QIPzjuRDgnpShpd6uS0jz5cP7BgwDU

###
PUT http://localhost:4444/api/posts/60d8298aec36130a18c4b611
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ4Mjk1ZmVjMzYxMzBhMThjNGI2MTAiLCJpYXQiOjE2MjQ3NzkxMDN9._f2Lvpme7dPM_QIPzjuRDgnpShpd6uS0jz5cP7BgwDU
Content-Type: application/json

{
    "title": "put first 2 3",
    "description": "this is first post of Thuy"
}

###
DELETE  http://localhost:4444/api/posts/60d8298aec36130a18c4b611
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ4Mjk1ZmVjMzYxMzBhMThjNGI2MTAiLCJpYXQiOjE2MjQ3NzkxMDN9._f2Lvpme7dPM_QIPzjuRDgnpShpd6uS0jz5cP7BgwDU
Content-Type: application/json
