
POST http://localhost:4444/api/auth/login
Content-Type: application/json

{
    "username": "thaiku77",
    "password": "123456"
}

###
POST http://localhost:4444/api/auth/register
Content-Type: application/json

{
    "username": "ngoquangthai29112001@gmail.com",
    "name": "ngoquangthai29112001",
    "password": "123456"
}
###

GET http://localhost:4444/api/auth
Authorization: Bearer .eyJ1c2VySWQiOiI2MGQ4MjE5OTllOWE3MzJhMjAwZGZhZDciLCJpYXQiOjE2MjQ3NzczNTN9.Suimu-esLFttXUoXNP61PM9a1g4AwE_ym5aaiDsDoQ4

###
GET http://localhost:4444/api/conversations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRjYThjZDMwNWFjNzA4OTg5N2M4ZmEiLCJpYXQiOjE2MjU2NTM3ODd9.eys3nxTVS3QJ36YA8NSqjGB2IcJasR9k7BaCFltmphs
Content-Type: application/json

###
POST http://localhost:4444/api/conversations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU1ODBiZGM5YWJhYzFiMmM2YjA1YjkiLCJpYXQiOjE2MjY0MzA2OTZ9.ex3MyY6jGTMXNAmMjjAwdUliWzcKGF4ZA66hjI1RI44
Content-Type: application/json

{
    "sender": "60dca8cd305ac7089897c8fa",
    "x": "60e580bdc9abac1b2c6b05b9"
}

###
GET http://localhost:4444/api/messages/60e59024bbad7d31840b60cc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRjYThjZDMwNWFjNzA4OTg5N2M4ZmEiLCJpYXQiOjE2MjU2NTM3ODd9.eys3nxTVS3QJ36YA8NSqjGB2IcJasR9k7BaCFltmphs

###
POST http://localhost:4444/api/messages/60e59024bbad7d31840b60cc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRjYThjZDMwNWFjNzA4OTg5N2M4ZmEiLCJpYXQiOjE2MjU2NTM3ODd9.eys3nxTVS3QJ36YA8NSqjGB2IcJasR9k7BaCFltmphs
Content-Type: application/json

{
    "message": "Cậu xinh thế hihi"
}

###
GET http://localhost:4444/api/username
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRjYThjZDMwNWFjNzA4OTg5N2M4ZmEiLCJpYXQiOjE2MjU2NTM3ODd9.eys3nxTVS3QJ36YA8NSqjGB2IcJasR9k7BaCFltmphs
Content-Type: application/json

###
GET http://localhost:4444/api/notificationMessage/60f15dc3640e982b34e8f2fb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU1ODBiZGM5YWJhYzFiMmM2YjA1YjkiLCJpYXQiOjE2MjY0MzA2OTZ9.ex3MyY6jGTMXNAmMjjAwdUliWzcKGF4ZA66hjI1RI44

###
PUT http://localhost:4444/api/notificationMessage/60f15dc3640e982b34e8f2fb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU1ODBiZGM5YWJhYzFiMmM2YjA1YjkiLCJpYXQiOjE2MjY0MzA2OTZ9.ex3MyY6jGTMXNAmMjjAwdUliWzcKGF4ZA66hjI1RI44
Content-Type: application/json

{
    "numberOfUserInNotifyMessage": "1",
    "numberMessageRead": "17"
}