POST http://localhost:4444/api/auth/login
Content-Type: application/json

{
    "username": "thaiabc",
    "password": "1234"
}

###
POST http://localhost:4444/api/auth/register
Content-Type: application/json

{
    "username": "thaithuytb",
    "password": "1234"
}

###
POST http://localhost:4444/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGM4YzdlMzc1OGFiOTE1YThkZWU5ZGUiLCJpYXQiOjE2MjM3NzExMDh9.Jrd82IGi_wHL64og4RyRcaOg6W8Mc5-Ydk4XMf2y3p0